INFO 2025-09-11 15:53:46,746 autoreload 37360 17344 Watching for file changes with StatReloader
INFO 2025-09-11 15:54:55,815 autoreload 37360 17344 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\core\settings.py changed, reloading.
INFO 2025-09-11 15:54:56,653 autoreload 37860 37148 Watching for file changes with StatReloader
INFO 2025-09-11 15:55:56,874 autoreload 37860 37148 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\core\settings.py changed, reloading.
INFO 2025-09-11 15:55:57,861 autoreload 33144 19576 Watching for file changes with StatReloader
INFO 2025-09-11 15:56:13,958 autoreload 33144 19576 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\core\settings.py changed, reloading.
INFO 2025-09-11 15:56:14,777 autoreload 37860 1544 Watching for file changes with StatReloader
WARNING 2025-09-11 15:56:31,077 base 37860 30344 Session data corrupted
INFO 2025-09-11 15:56:31,086 basehttp 37860 30344 "GET / HTTP/1.1" 302 0
INFO 2025-09-11 15:56:31,099 basehttp 37860 30344 "GET /auditorias/ HTTP/1.1" 302 0
INFO 2025-09-11 15:56:31,120 basehttp 37860 30344 "GET /login/?next=/auditorias/ HTTP/1.1" 200 3431
INFO 2025-09-11 15:56:31,143 basehttp 37860 30344 "GET /static/css/login.css HTTP/1.1" 304 0
INFO 2025-09-11 15:56:31,148 basehttp 37860 30344 "GET /static/img/imagem2.png HTTP/1.1" 304 0
INFO 2025-09-11 15:56:31,148 basehttp 37860 35720 "GET /static/js/login.js HTTP/1.1" 304 0
INFO 2025-09-11 15:56:37,437 basehttp 37860 35720 "POST /login/?next=/auditorias/ HTTP/1.1" 302 0
ERROR 2025-09-11 15:56:37,610 log 37860 35720 Internal Server Error: /auditorias/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 39, in dashboard_auditorias
    return render(request, 'auditorias/dashboard.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: auditorias/dashboard.html
ERROR 2025-09-11 15:56:37,614 basehttp 37860 35720 "GET /auditorias/ HTTP/1.1" 500 98046
ERROR 2025-09-11 15:58:45,401 log 37860 35720 Internal Server Error: /auditorias/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 39, in dashboard_auditorias
    return render(request, 'auditorias/dashboard.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: auditorias/dashboard.html
ERROR 2025-09-11 15:58:45,403 basehttp 37860 35720 "GET /auditorias/ HTTP/1.1" 500 97734
ERROR 2025-09-11 15:58:46,787 log 37860 35720 Internal Server Error: /auditorias/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 39, in dashboard_auditorias
    return render(request, 'auditorias/dashboard.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: auditorias/dashboard.html
ERROR 2025-09-11 15:58:46,789 basehttp 37860 35720 "GET /auditorias/ HTTP/1.1" 500 97734
ERROR 2025-09-11 15:58:47,586 log 37860 35720 Internal Server Error: /auditorias/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 39, in dashboard_auditorias
    return render(request, 'auditorias/dashboard.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: auditorias/dashboard.html
ERROR 2025-09-11 15:58:47,587 basehttp 37860 35720 "GET /auditorias/ HTTP/1.1" 500 97734
ERROR 2025-09-11 15:59:19,297 log 37860 35720 Internal Server Error: /auditorias/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: auditorias/base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 39, in dashboard_auditorias
    return render(request, 'auditorias/dashboard.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: auditorias/base.html
ERROR 2025-09-11 15:59:19,301 basehttp 37860 35720 "GET /auditorias/ HTTP/1.1" 500 151932
ERROR 2025-09-11 15:59:22,565 log 37860 35720 Internal Server Error: /auditorias/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: auditorias/base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 39, in dashboard_auditorias
    return render(request, 'auditorias/dashboard.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: auditorias/base.html
ERROR 2025-09-11 15:59:22,568 basehttp 37860 35720 "GET /auditorias/ HTTP/1.1" 500 151932
ERROR 2025-09-11 15:59:35,467 log 37860 35720 Internal Server Error: /auditorias/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: auditorias/base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 39, in dashboard_auditorias
    return render(request, 'auditorias/dashboard.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: auditorias/base.html
ERROR 2025-09-11 15:59:35,470 basehttp 37860 35720 "GET /auditorias/ HTTP/1.1" 500 151932
ERROR 2025-09-11 15:59:44,267 log 37860 35720 Internal Server Error: /auditorias/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: auditorias/base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 39, in dashboard_auditorias
    return render(request, 'auditorias/dashboard.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: auditorias/base.html
ERROR 2025-09-11 15:59:44,269 basehttp 37860 35720 "GET /auditorias/ HTTP/1.1" 500 151932
INFO 2025-09-11 15:59:59,672 basehttp 37860 35720 "GET /auditorias/ HTTP/1.1" 200 36732
ERROR 2025-09-11 16:00:06,365 log 37860 35720 Internal Server Error: /auditorias/checklists/criar/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 686, in criar_checklist
    return render(request, 'auditorias/checklists/form.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: auditorias/checklists/form.html
ERROR 2025-09-11 16:00:06,367 basehttp 37860 35720 "GET /auditorias/checklists/criar/ HTTP/1.1" 500 98054
ERROR 2025-09-11 16:00:17,813 log 37860 35720 Internal Server Error: /auditorias/auditorias/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 907, in lista_auditorias
    return render(request, 'auditorias/auditorias/lista.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: auditorias/auditorias/lista.html
ERROR 2025-09-11 16:00:17,815 basehttp 37860 35720 "GET /auditorias/auditorias/ HTTP/1.1" 500 98575
INFO 2025-09-11 16:00:21,360 basehttp 37860 35720 "GET /itens/ HTTP/1.1" 200 31964
ERROR 2025-09-11 16:00:22,831 log 37860 35720 Internal Server Error: /auditorias/pilares/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 66, in lista_pilares
    return render(request, 'auditorias/pilares/lista.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: auditorias/pilares/lista.html
ERROR 2025-09-11 16:00:22,832 basehttp 37860 35720 "GET /auditorias/pilares/ HTTP/1.1" 500 98350
ERROR 2025-09-11 16:00:25,256 log 37860 35720 Internal Server Error: /auditorias/pilares/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 66, in lista_pilares
    return render(request, 'auditorias/pilares/lista.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: auditorias/pilares/lista.html
ERROR 2025-09-11 16:00:25,257 basehttp 37860 35720 "GET /auditorias/pilares/ HTTP/1.1" 500 98350
ERROR 2025-09-11 16:00:29,678 log 37860 35720 Internal Server Error: /auditorias/normas/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 267, in lista_normas
    return render(request, 'auditorias/normas/lista.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: auditorias/normas/lista.html
ERROR 2025-09-11 16:00:29,680 basehttp 37860 35720 "GET /auditorias/normas/ HTTP/1.1" 500 98305
INFO 2025-09-11 16:00:42,713 basehttp 37860 35720 "GET /itens/ HTTP/1.1" 200 31964
INFO 2025-09-11 16:00:59,994 basehttp 37860 35720 "GET /itens/?search= HTTP/1.1" 200 31964
ERROR 2025-09-11 16:01:03,706 log 37860 35720 Internal Server Error: /auditorias/categorias/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 162, in lista_categorias_auditoria
    return render(request, 'auditorias/categorias/lista.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: auditorias/categorias/lista.html
ERROR 2025-09-11 16:01:03,708 basehttp 37860 35720 "GET /auditorias/categorias/ HTTP/1.1" 500 98664
INFO 2025-09-11 16:01:08,613 basehttp 37860 35720 "GET /auditorias/ HTTP/1.1" 200 36732
ERROR 2025-09-11 16:01:12,923 log 37860 35720 Internal Server Error: /auditorias/auditorias/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 907, in lista_auditorias
    return render(request, 'auditorias/auditorias/lista.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: auditorias/auditorias/lista.html
ERROR 2025-09-11 16:01:12,925 basehttp 37860 35720 "GET /auditorias/auditorias/ HTTP/1.1" 500 98575
INFO 2025-09-11 16:02:32,478 basehttp 37860 35720 "GET /auditorias/ HTTP/1.1" 200 36732
INFO 2025-09-11 16:02:37,120 basehttp 37860 35720 "GET /auditorias/ HTTP/1.1" 200 36732
INFO 2025-09-11 16:14:46,545 autoreload 25860 33232 Watching for file changes with StatReloader
INFO 2025-09-11 16:14:47,263 basehttp 25860 11692 "GET /auditorias/ HTTP/1.1" 200 36732
ERROR 2025-09-11 16:14:49,448 log 25860 11692 Internal Server Error: /auditorias/auditorias/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 907, in lista_auditorias
    return render(request, 'auditorias/auditorias/lista.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: auditorias/auditorias/lista.html
ERROR 2025-09-11 16:14:49,451 basehttp 25860 11692 "GET /auditorias/auditorias/ HTTP/1.1" 500 98574
INFO 2025-09-11 16:18:17,660 autoreload 37536 31196 Watching for file changes with StatReloader
ERROR 2025-09-11 16:18:18,670 log 37536 19440 Internal Server Error: /auditorias/auditorias/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 907, in lista_auditorias
    return render(request, 'auditorias/auditorias/lista.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: auditorias/auditorias/lista.html
ERROR 2025-09-11 16:18:18,674 basehttp 37536 19440 "GET /auditorias/auditorias/ HTTP/1.1" 500 98412
INFO 2025-09-11 16:18:27,517 autoreload 37536 31196 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\urls.py changed, reloading.
INFO 2025-09-11 16:18:28,336 autoreload 32752 1632 Watching for file changes with StatReloader
ERROR 2025-09-11 16:18:35,657 log 32752 16924 Internal Server Error: /itens/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\itens\views.py", line 40, in lista_itens
    return render(request, 'itens/lista_itens.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'lista_categorias_auditoria' not found. 'lista_categorias_auditoria' is not a valid view function or pattern name.
ERROR 2025-09-11 16:18:35,664 basehttp 32752 16924 "GET /itens/ HTTP/1.1" 500 195396
ERROR 2025-09-11 16:18:40,413 log 32752 16924 Internal Server Error: /auditorias/pilares/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 66, in lista_pilares
    return render(request, 'auditorias/pilares/lista.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'lista_categorias_auditoria' not found. 'lista_categorias_auditoria' is not a valid view function or pattern name.
ERROR 2025-09-11 16:18:40,417 basehttp 32752 16924 "GET /auditorias/pilares/ HTTP/1.1" 500 195611
WARNING 2025-09-11 16:18:43,804 log 32752 16924 Not Found: /auditorias/categorias/
WARNING 2025-09-11 16:18:43,805 basehttp 32752 16924 "GET /auditorias/categorias/ HTTP/1.1" 404 15464
ERROR 2025-09-11 16:18:46,683 log 32752 16924 Internal Server Error: /auditorias/normas/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 267, in lista_normas
    return render(request, 'auditorias/normas/lista.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'lista_categorias_auditoria' not found. 'lista_categorias_auditoria' is not a valid view function or pattern name.
ERROR 2025-09-11 16:18:46,686 basehttp 32752 16924 "GET /auditorias/normas/ HTTP/1.1" 500 193734
ERROR 2025-09-11 16:18:49,127 log 32752 16924 Internal Server Error: /auditorias/ferramentas-digitais/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 361, in lista_ferramentas_digitais
    return render(request, 'auditorias/ferramentas_digitais/lista.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'lista_categorias_auditoria' not found. 'lista_categorias_auditoria' is not a valid view function or pattern name.
ERROR 2025-09-11 16:18:49,130 basehttp 32752 16924 "GET /auditorias/ferramentas-digitais/ HTTP/1.1" 500 194092
ERROR 2025-09-11 16:18:56,840 log 32752 16924 Internal Server Error: /auditorias/tipos-questao/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 449, in lista_tipos_questao
    return render(request, 'auditorias/tipos_questao/lista.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'lista_categorias_auditoria' not found. 'lista_categorias_auditoria' is not a valid view function or pattern name.
ERROR 2025-09-11 16:18:56,843 basehttp 32752 16924 "GET /auditorias/tipos-questao/ HTTP/1.1" 500 194217
ERROR 2025-09-11 16:20:18,784 log 32752 16924 Internal Server Error: /auditorias/auditorias/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 907, in lista_auditorias
    return render(request, 'auditorias/auditorias/lista.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'lista_categorias_auditoria' not found. 'lista_categorias_auditoria' is not a valid view function or pattern name.
ERROR 2025-09-11 16:20:18,787 basehttp 32752 16924 "GET /auditorias/auditorias/ HTTP/1.1" 500 195097
INFO 2025-09-11 16:22:07,612 autoreload 32752 1632 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\urls.py changed, reloading.
INFO 2025-09-11 16:22:08,398 autoreload 36564 32104 Watching for file changes with StatReloader
INFO 2025-09-11 16:22:13,209 basehttp 36564 31424 "GET /auditorias/auditorias/ HTTP/1.1" 200 32107
INFO 2025-09-11 16:22:15,872 basehttp 36564 31424 "GET /itens/ HTTP/1.1" 200 31974
INFO 2025-09-11 16:22:16,982 basehttp 36564 31424 "GET /auditorias/pilares/ HTTP/1.1" 200 37487
INFO 2025-09-11 16:22:18,047 basehttp 36564 31424 "GET /auditorias/categorias/ HTTP/1.1" 200 32140
INFO 2025-09-11 16:22:19,424 basehttp 36564 31424 "GET /auditorias/normas/ HTTP/1.1" 200 31953
INFO 2025-09-11 16:22:20,042 basehttp 36564 31424 "GET /auditorias/ferramentas-digitais/ HTTP/1.1" 200 32962
INFO 2025-09-11 16:22:23,562 basehttp 36564 31424 "GET /auditorias/ferramentas-digitais/1/editar/ HTTP/1.1" 200 40388
INFO 2025-09-11 16:22:26,291 basehttp 36564 31424 "GET /auditorias/ferramentas-digitais/1/editar/ HTTP/1.1" 200 40388
INFO 2025-09-11 16:22:27,091 basehttp 36564 31424 "GET /auditorias/ferramentas-digitais/1/editar/ HTTP/1.1" 200 40388
INFO 2025-09-11 16:22:27,556 basehttp 36564 31424 "GET /auditorias/ferramentas-digitais/1/editar/ HTTP/1.1" 200 40388
INFO 2025-09-11 16:22:28,202 basehttp 36564 31424 "POST /auditorias/ferramentas-digitais/1/editar/ HTTP/1.1" 302 0
INFO 2025-09-11 16:22:28,218 basehttp 36564 31424 "GET /auditorias/ferramentas-digitais/ HTTP/1.1" 200 33245
INFO 2025-09-11 16:22:30,907 basehttp 36564 31424 "GET /auditorias/normas/ HTTP/1.1" 200 31953
INFO 2025-09-11 16:22:32,044 basehttp 36564 31424 "GET /auditorias/ferramentas-digitais/ HTTP/1.1" 200 32962
ERROR 2025-09-11 16:22:35,424 log 36564 31424 Internal Server Error: /auditorias/ferramentas-digitais/1/deletar/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 422, in deletar_ferramenta_digital
    return render(request, 'auditorias/ferramentas_digitais/deletar.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: auditorias/ferramentas_digitais/deletar.html
ERROR 2025-09-11 16:22:35,428 basehttp 36564 31424 "GET /auditorias/ferramentas-digitais/1/deletar/ HTTP/1.1" 500 98805
ERROR 2025-09-11 16:22:51,545 log 36564 31424 Internal Server Error: /auditorias/modelos-auditoria/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 769, in lista_modelos_auditoria
    return render(request, 'auditorias/modelos_auditoria/lista.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: auditorias/modelos_auditoria/lista.html
ERROR 2025-09-11 16:22:51,547 basehttp 36564 31424 "GET /auditorias/modelos-auditoria/ HTTP/1.1" 500 98928
INFO 2025-09-11 16:22:56,183 basehttp 36564 31424 "GET /auditorias/checklists/ HTTP/1.1" 200 33142
INFO 2025-09-11 16:23:01,586 basehttp 36564 31424 "GET /auditorias/dashboard/ HTTP/1.1" 200 36742
INFO 2025-09-11 16:23:02,024 basehttp 36564 31424 "GET /auditorias/auditorias/ HTTP/1.1" 200 32107
INFO 2025-09-11 16:23:02,595 basehttp 36564 31424 "GET /auditorias/dashboard/ HTTP/1.1" 200 36742
INFO 2025-09-11 16:23:04,292 basehttp 36564 31424 "GET /auditorias/auditorias/ HTTP/1.1" 200 32107
INFO 2025-09-11 16:23:05,490 basehttp 36564 31424 "GET /itens/ HTTP/1.1" 200 31974
INFO 2025-09-11 16:23:06,261 basehttp 36564 31424 "GET /auditorias/pilares/ HTTP/1.1" 200 37487
INFO 2025-09-11 16:23:06,899 basehttp 36564 31424 "GET /auditorias/categorias/ HTTP/1.1" 200 32140
INFO 2025-09-11 16:23:07,537 basehttp 36564 31424 "GET /auditorias/normas/ HTTP/1.1" 200 31953
INFO 2025-09-11 16:23:08,291 basehttp 36564 31424 "GET /auditorias/ferramentas-digitais/ HTTP/1.1" 200 32962
INFO 2025-09-11 16:23:09,282 basehttp 36564 31424 "GET /auditorias/tipos-questao/ HTTP/1.1" 200 32068
INFO 2025-09-11 16:23:09,966 basehttp 36564 31424 "GET /auditorias/modelos-avaliacao/ HTTP/1.1" 200 33235
INFO 2025-09-11 16:23:10,772 basehttp 36564 31424 "GET /auditorias/checklists/ HTTP/1.1" 200 33142
ERROR 2025-09-11 16:23:12,108 log 36564 31424 Internal Server Error: /auditorias/modelos-auditoria/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 769, in lista_modelos_auditoria
    return render(request, 'auditorias/modelos_auditoria/lista.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: auditorias/modelos_auditoria/lista.html
ERROR 2025-09-11 16:23:12,110 basehttp 36564 31424 "GET /auditorias/modelos-auditoria/ HTTP/1.1" 500 98918
ERROR 2025-09-11 16:23:15,806 log 36564 31424 Internal Server Error: /auditorias/checklists/1/deletar/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 744, in deletar_checklist
    return render(request, 'auditorias/checklists/deletar.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: auditorias/checklists/deletar.html
ERROR 2025-09-11 16:23:15,808 basehttp 36564 31424 "GET /auditorias/checklists/1/deletar/ HTTP/1.1" 500 98294
INFO 2025-09-11 16:24:02,009 autoreload 36564 32104 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py changed, reloading.
INFO 2025-09-11 16:24:02,882 autoreload 31156 15740 Watching for file changes with StatReloader
INFO 2025-09-11 16:24:32,575 autoreload 31156 15740 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py changed, reloading.
INFO 2025-09-11 16:24:33,398 autoreload 32160 16912 Watching for file changes with StatReloader
INFO 2025-09-11 16:24:54,870 autoreload 32160 16912 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py changed, reloading.
INFO 2025-09-11 16:24:55,780 autoreload 33452 37592 Watching for file changes with StatReloader
INFO 2025-09-11 16:25:17,101 autoreload 33452 37592 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py changed, reloading.
INFO 2025-09-11 16:25:17,892 autoreload 37648 5076 Watching for file changes with StatReloader
INFO 2025-09-11 16:27:22,005 autoreload 37648 5076 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py changed, reloading.
INFO 2025-09-11 16:27:22,829 autoreload 22452 23508 Watching for file changes with StatReloader
INFO 2025-09-11 16:29:25,911 autoreload 22452 23508 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py changed, reloading.
INFO 2025-09-11 16:29:26,907 autoreload 14452 35392 Watching for file changes with StatReloader
INFO 2025-09-11 16:35:19,659 autoreload 14452 35392 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py changed, reloading.
INFO 2025-09-11 16:35:20,539 autoreload 16924 18832 Watching for file changes with StatReloader
INFO 2025-09-11 16:35:30,468 autoreload 16924 18832 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py changed, reloading.
INFO 2025-09-11 16:35:31,332 autoreload 22288 32652 Watching for file changes with StatReloader
INFO 2025-09-11 16:35:43,347 autoreload 22288 32652 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py changed, reloading.
INFO 2025-09-11 16:35:44,220 autoreload 23212 6752 Watching for file changes with StatReloader
INFO 2025-09-11 16:35:56,290 autoreload 23212 6752 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py changed, reloading.
INFO 2025-09-11 16:35:57,159 autoreload 35448 20604 Watching for file changes with StatReloader
INFO 2025-09-11 16:36:09,307 autoreload 35448 20604 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py changed, reloading.
INFO 2025-09-11 16:36:10,152 autoreload 27748 4140 Watching for file changes with StatReloader
INFO 2025-09-11 16:36:19,015 autoreload 27748 4140 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py changed, reloading.
INFO 2025-09-11 16:36:19,960 autoreload 33504 8904 Watching for file changes with StatReloader
INFO 2025-09-11 16:36:30,893 autoreload 33504 8904 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py changed, reloading.
INFO 2025-09-11 16:36:31,645 autoreload 37068 17564 Watching for file changes with StatReloader
INFO 2025-09-11 16:36:46,782 autoreload 37068 17564 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py changed, reloading.
INFO 2025-09-11 16:36:47,681 autoreload 5720 29664 Watching for file changes with StatReloader
INFO 2025-09-11 16:36:59,654 autoreload 5720 29664 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py changed, reloading.
INFO 2025-09-11 16:37:00,485 autoreload 25416 31772 Watching for file changes with StatReloader
INFO 2025-09-11 16:37:07,333 basehttp 25416 32652 "GET /auditorias/checklists/ HTTP/1.1" 200 33142
INFO 2025-09-11 16:37:10,047 basehttp 25416 32652 "GET /auditorias/checklists/1/deletar/ HTTP/1.1" 200 26600
INFO 2025-09-11 16:37:12,127 basehttp 25416 32652 "POST /auditorias/checklists/1/deletar/ HTTP/1.1" 302 0
INFO 2025-09-11 16:37:12,142 basehttp 25416 32652 "GET /auditorias/checklists/ HTTP/1.1" 200 32269
INFO 2025-09-11 16:37:14,773 basehttp 25416 32652 "GET /auditorias/modelos-avaliacao/ HTTP/1.1" 200 33235
INFO 2025-09-11 16:37:20,066 basehttp 25416 32652 "GET /auditorias/modelos-avaliacao/1/deletar/ HTTP/1.1" 200 26621
INFO 2025-09-11 16:37:20,889 basehttp 25416 32652 "POST /auditorias/modelos-avaliacao/1/deletar/ HTTP/1.1" 302 0
INFO 2025-09-11 16:37:20,909 basehttp 25416 32652 "GET /auditorias/modelos-avaliacao/ HTTP/1.1" 200 32407
INFO 2025-09-11 16:37:23,152 basehttp 25416 32652 "GET /auditorias/tipos-questao/ HTTP/1.1" 200 32068
INFO 2025-09-11 16:37:23,642 basehttp 25416 32652 "GET /auditorias/modelos-avaliacao/ HTTP/1.1" 200 32123
INFO 2025-09-11 16:37:24,203 basehttp 25416 32652 "GET /auditorias/checklists/ HTTP/1.1" 200 31997
ERROR 2025-09-11 16:37:24,752 log 25416 32652 Internal Server Error: /auditorias/modelos-auditoria/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 768, in lista_modelos_auditoria
    return render(request, 'auditorias/modelos_auditoria/lista.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: auditorias/modelos_auditoria/lista.html
ERROR 2025-09-11 16:37:24,756 basehttp 25416 32652 "GET /auditorias/modelos-auditoria/ HTTP/1.1" 500 98918
ERROR 2025-09-11 16:37:42,245 log 25416 32652 Internal Server Error: /auditorias/modelos-auditoria/
Traceback (most recent call last):
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py", line 768, in lista_modelos_auditoria
    return render(request, 'auditorias/modelos_auditoria/lista.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FG3454\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: auditorias/modelos_auditoria/lista.html
ERROR 2025-09-11 16:37:42,246 basehttp 25416 32652 "GET /auditorias/modelos-auditoria/ HTTP/1.1" 500 98918
INFO 2025-09-11 16:38:44,470 basehttp 25416 32652 "GET /auditorias/tipos-questao/ HTTP/1.1" 200 32068
INFO 2025-09-11 16:38:45,576 basehttp 25416 32652 "GET /auditorias/modelos-avaliacao/ HTTP/1.1" 200 32123
INFO 2025-09-11 16:38:46,464 basehttp 25416 32652 "GET /auditorias/checklists/ HTTP/1.1" 200 31997
INFO 2025-09-11 16:38:47,368 basehttp 25416 32652 "GET /auditorias/modelos-auditoria/ HTTP/1.1" 200 32101
INFO 2025-09-11 16:38:49,421 basehttp 25416 32652 "GET /auditorias/checklists/ HTTP/1.1" 200 31997
INFO 2025-09-11 16:38:49,860 basehttp 25416 32652 "GET /auditorias/modelos-avaliacao/ HTTP/1.1" 200 32123
INFO 2025-09-11 16:38:50,273 basehttp 25416 32652 "GET /auditorias/tipos-questao/ HTTP/1.1" 200 32068
INFO 2025-09-11 16:38:50,791 basehttp 25416 32652 "GET /auditorias/ferramentas-digitais/ HTTP/1.1" 200 32962
INFO 2025-09-11 16:38:51,237 basehttp 25416 32652 "GET /auditorias/normas/ HTTP/1.1" 200 31953
INFO 2025-09-11 16:38:51,706 basehttp 25416 32652 "GET /auditorias/ferramentas-digitais/ HTTP/1.1" 200 32962
INFO 2025-09-11 16:38:53,754 basehttp 25416 32652 "GET /auditorias/ferramentas-digitais/1/deletar/ HTTP/1.1" 200 26616
INFO 2025-09-11 16:38:54,556 basehttp 25416 32652 "POST /auditorias/ferramentas-digitais/1/deletar/ HTTP/1.1" 302 0
INFO 2025-09-11 16:38:54,571 basehttp 25416 32652 "GET /auditorias/ferramentas-digitais/ HTTP/1.1" 200 32382
INFO 2025-09-11 16:38:55,471 basehttp 25416 32652 "GET /auditorias/ferramentas-digitais/ HTTP/1.1" 200 32101
INFO 2025-09-11 16:38:56,981 basehttp 25416 32652 "GET /auditorias/ferramentas-digitais/ HTTP/1.1" 200 32101
INFO 2025-09-11 16:38:57,230 basehttp 25416 32652 "GET /auditorias/ferramentas-digitais/ HTTP/1.1" 200 32101
INFO 2025-09-11 16:38:58,035 basehttp 25416 32652 "GET /auditorias/ferramentas-digitais/ HTTP/1.1" 200 32101
INFO 2025-09-11 16:38:58,206 basehttp 25416 32652 "GET /auditorias/ferramentas-digitais/ HTTP/1.1" 200 32101
INFO 2025-09-11 16:38:58,389 basehttp 25416 32652 "GET /auditorias/ferramentas-digitais/ HTTP/1.1" 200 32101
INFO 2025-09-11 16:38:58,578 basehttp 25416 32652 "GET /auditorias/ferramentas-digitais/ HTTP/1.1" 200 32101
INFO 2025-09-11 16:38:58,778 basehttp 25416 32652 "GET /auditorias/ferramentas-digitais/ HTTP/1.1" 200 32101
INFO 2025-09-11 16:38:58,974 basehttp 25416 32652 "GET /auditorias/ferramentas-digitais/ HTTP/1.1" 200 32101
INFO 2025-09-11 16:38:59,747 basehttp 25416 32652 "GET /auditorias/ferramentas-digitais/?search= HTTP/1.1" 200 32101
INFO 2025-09-11 16:39:00,235 basehttp 25416 32652 "GET /auditorias/ferramentas-digitais/?search= HTTP/1.1" 200 32101
INFO 2025-09-11 16:39:00,609 basehttp 25416 32652 "GET /auditorias/ferramentas-digitais/?search= HTTP/1.1" 200 32101
INFO 2025-09-11 16:39:03,855 basehttp 25416 32652 "GET /auditorias/pilares/ HTTP/1.1" 200 37487
INFO 2025-09-11 16:39:04,517 basehttp 25416 32652 "GET /auditorias/categorias/ HTTP/1.1" 200 32140
INFO 2025-09-11 16:39:05,639 basehttp 25416 32652 "GET /auditorias/categorias/ HTTP/1.1" 200 32140
INFO 2025-09-11 16:39:06,066 basehttp 25416 32652 "GET /auditorias/categorias/ HTTP/1.1" 200 32140
INFO 2025-09-11 16:39:06,800 basehttp 25416 32652 "GET /auditorias/categorias/ HTTP/1.1" 200 32140
INFO 2025-09-11 16:39:07,047 basehttp 25416 32652 "GET /auditorias/categorias/ HTTP/1.1" 200 32140
INFO 2025-09-11 16:39:07,219 basehttp 25416 32652 "GET /auditorias/categorias/ HTTP/1.1" 200 32140
INFO 2025-09-11 16:39:07,407 basehttp 25416 32652 "GET /auditorias/categorias/ HTTP/1.1" 200 32140
INFO 2025-09-11 16:39:08,607 basehttp 25416 32652 "GET /itens/ HTTP/1.1" 200 31974
INFO 2025-09-11 16:39:11,736 basehttp 25416 32652 "GET /auditorias/auditorias/ HTTP/1.1" 200 32107
INFO 2025-09-11 16:39:12,485 basehttp 25416 32652 "GET /auditorias/auditorias/ HTTP/1.1" 200 32107
INFO 2025-09-11 16:39:13,350 basehttp 25416 32652 "GET /auditorias/auditorias/ HTTP/1.1" 200 32107
INFO 2025-09-11 16:39:13,577 basehttp 25416 32652 "GET /auditorias/auditorias/ HTTP/1.1" 200 32107
INFO 2025-09-11 16:39:13,758 basehttp 25416 32652 "GET /auditorias/auditorias/ HTTP/1.1" 200 32107
INFO 2025-09-11 16:39:15,398 basehttp 25416 32652 "GET /auditorias/dashboard/ HTTP/1.1" 200 36742
INFO 2025-09-11 16:39:18,037 basehttp 25416 32652 "GET /auditorias/auditorias/criar/ HTTP/1.1" 200 48734
INFO 2025-09-11 16:39:30,648 basehttp 25416 32652 "GET /auditorias/auditorias/criar/ HTTP/1.1" 200 48734
INFO 2025-09-11 16:39:32,181 basehttp 25416 32652 "GET /auditorias/dashboard/ HTTP/1.1" 200 36742
INFO 2025-09-11 16:39:33,581 basehttp 25416 32652 "GET /auditorias/auditorias/ HTTP/1.1" 200 32107
INFO 2025-09-11 16:40:06,954 basehttp 25416 32652 "GET /itens/ HTTP/1.1" 200 31974
INFO 2025-09-11 16:40:07,892 basehttp 25416 32652 "GET /auditorias/pilares/ HTTP/1.1" 200 37487
INFO 2025-09-11 16:40:08,648 basehttp 25416 32652 "GET /auditorias/categorias/ HTTP/1.1" 200 32140
INFO 2025-09-11 16:40:09,814 basehttp 25416 32652 "GET /auditorias/categorias/ HTTP/1.1" 200 32140
INFO 2025-09-11 16:40:10,461 basehttp 25416 32652 "GET /auditorias/categorias/ HTTP/1.1" 200 32140
INFO 2025-09-11 16:40:10,684 basehttp 25416 32652 "GET /auditorias/categorias/ HTTP/1.1" 200 32140
INFO 2025-09-11 16:40:10,861 basehttp 25416 32652 "GET /auditorias/categorias/ HTTP/1.1" 200 32140
INFO 2025-09-11 16:40:11,070 basehttp 25416 32652 "GET /auditorias/categorias/ HTTP/1.1" 200 32140
INFO 2025-09-11 16:40:11,268 basehttp 25416 32652 "GET /auditorias/categorias/ HTTP/1.1" 200 32140
INFO 2025-09-11 16:40:11,467 basehttp 25416 32652 "GET /auditorias/categorias/ HTTP/1.1" 200 32140
INFO 2025-09-11 16:40:11,761 basehttp 25416 32652 "GET /auditorias/categorias/ HTTP/1.1" 200 32140
INFO 2025-09-11 16:40:11,971 basehttp 25416 32652 "GET /auditorias/categorias/ HTTP/1.1" 200 32140
INFO 2025-09-11 16:40:12,167 basehttp 25416 32652 "GET /auditorias/categorias/ HTTP/1.1" 200 32140
INFO 2025-09-11 16:40:12,353 basehttp 25416 32652 "GET /auditorias/categorias/ HTTP/1.1" 200 32140
INFO 2025-09-11 16:40:14,992 basehttp 25416 32652 "GET /auditorias/normas/ HTTP/1.1" 200 31953
INFO 2025-09-11 16:40:16,021 basehttp 25416 32652 "GET /auditorias/ferramentas-digitais/ HTTP/1.1" 200 32101
INFO 2025-09-11 16:40:17,309 basehttp 25416 32652 "GET /auditorias/tipos-questao/ HTTP/1.1" 200 32068
INFO 2025-09-11 16:40:17,979 basehttp 25416 32652 "GET /auditorias/modelos-avaliacao/ HTTP/1.1" 200 32123
INFO 2025-09-11 16:40:18,463 basehttp 25416 32652 "GET /auditorias/checklists/ HTTP/1.1" 200 31997
INFO 2025-09-11 16:40:18,976 basehttp 25416 32652 "GET /auditorias/modelos-auditoria/ HTTP/1.1" 200 32101
INFO 2025-09-11 16:40:20,907 basehttp 25416 32652 "GET /auditorias/dashboard/ HTTP/1.1" 200 36742
INFO 2025-09-11 16:40:23,503 basehttp 25416 32652 "GET /auditorias/auditorias/criar/ HTTP/1.1" 200 48734
INFO 2025-09-11 16:40:25,026 basehttp 25416 32652 "GET /auditorias/dashboard/ HTTP/1.1" 200 36742
INFO 2025-09-11 16:41:17,740 autoreload 25416 31772 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py changed, reloading.
INFO 2025-09-11 16:41:18,614 autoreload 6000 30248 Watching for file changes with StatReloader
INFO 2025-09-11 16:41:36,810 autoreload 6000 30248 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py changed, reloading.
INFO 2025-09-11 16:41:37,641 autoreload 11732 36876 Watching for file changes with StatReloader
INFO 2025-09-11 16:41:52,690 autoreload 11732 36876 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py changed, reloading.
INFO 2025-09-11 16:41:53,557 autoreload 34952 31280 Watching for file changes with StatReloader
INFO 2025-09-11 16:42:01,310 autoreload 34952 31280 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py changed, reloading.
INFO 2025-09-11 16:42:02,198 autoreload 26484 5848 Watching for file changes with StatReloader
INFO 2025-09-11 16:42:11,090 autoreload 26484 5848 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py changed, reloading.
INFO 2025-09-11 16:42:11,943 autoreload 12216 37024 Watching for file changes with StatReloader
INFO 2025-09-11 16:42:28,121 autoreload 12216 37024 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py changed, reloading.
INFO 2025-09-11 16:42:29,095 autoreload 36688 37580 Watching for file changes with StatReloader
INFO 2025-09-11 16:42:38,987 autoreload 36688 37580 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py changed, reloading.
INFO 2025-09-11 16:42:39,767 autoreload 33116 37124 Watching for file changes with StatReloader
INFO 2025-09-11 16:42:51,732 autoreload 33116 37124 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py changed, reloading.
INFO 2025-09-11 16:42:52,572 autoreload 32788 33748 Watching for file changes with StatReloader
INFO 2025-09-11 16:43:01,390 autoreload 32788 33748 H:\Programação\Em Andamento\Gestão kaizen SKF\Gestao-auditorias-django\auditorias\views.py changed, reloading.
INFO 2025-09-11 16:43:02,246 autoreload 12204 24520 Watching for file changes with StatReloader
INFO 2025-09-11 16:43:08,751 basehttp 12204 26104 "GET /auditorias/auditorias/criar/ HTTP/1.1" 200 48734
INFO 2025-09-11 16:43:10,384 basehttp 12204 26104 "GET /auditorias/auditorias/ HTTP/1.1" 200 32159
INFO 2025-09-11 16:43:11,075 basehttp 12204 26104 "GET /itens/ HTTP/1.1" 200 31974
INFO 2025-09-11 16:43:18,468 basehttp 12204 26104 "GET /itens/ HTTP/1.1" 200 31974
INFO 2025-09-11 16:43:20,508 basehttp 12204 26104 "GET /auditorias/pilares/ HTTP/1.1" 200 37531
INFO 2025-09-11 16:43:22,085 basehttp 12204 26104 "GET /auditorias/categorias/ HTTP/1.1" 200 32212
INFO 2025-09-11 16:43:25,495 basehttp 12204 26104 "GET /auditorias/normas/ HTTP/1.1" 200 31997
INFO 2025-09-11 16:43:27,779 basehttp 12204 26104 "GET /auditorias/ferramentas-digitais/ HTTP/1.1" 200 32171
INFO 2025-09-11 16:43:27,993 basehttp 12204 26104 "GET /auditorias/ferramentas-digitais/ HTTP/1.1" 200 32171
INFO 2025-09-11 16:43:31,278 basehttp 12204 26104 "GET /auditorias/tipos-questao/ HTTP/1.1" 200 32126
INFO 2025-09-11 16:44:02,841 basehttp 12204 26104 "GET /itens/ HTTP/1.1" 200 31974
INFO 2025-09-11 16:46:31,164 basehttp 12204 26104 "GET /itens/ HTTP/1.1" 200 31971
INFO 2025-09-11 16:46:32,271 basehttp 12204 26104 "GET /itens/criar/ HTTP/1.1" 200 43537
INFO 2025-09-11 16:46:35,434 basehttp 12204 26104 "GET /auditorias/auditorias/ HTTP/1.1" 200 32162
INFO 2025-09-11 16:46:36,571 basehttp 12204 26104 "GET /auditorias/auditorias/criar/ HTTP/1.1" 200 48734
INFO 2025-09-11 16:46:37,824 basehttp 12204 26104 "GET /auditorias/auditorias/criar/ HTTP/1.1" 200 48734
INFO 2025-09-11 16:46:38,923 basehttp 12204 26104 "GET /auditorias/categorias/ HTTP/1.1" 200 32205
INFO 2025-09-11 16:46:40,274 basehttp 12204 26104 "GET /auditorias/categorias/criar/ HTTP/1.1" 200 41467
INFO 2025-09-11 16:46:47,304 basehttp 12204 26104 "GET /auditorias/categorias/ HTTP/1.1" 200 32205
INFO 2025-09-11 16:46:47,710 basehttp 12204 26104 "GET /auditorias/normas/ HTTP/1.1" 200 32000
INFO 2025-09-11 16:46:48,271 basehttp 12204 26104 "GET /auditorias/ferramentas-digitais/ HTTP/1.1" 200 32175
INFO 2025-09-11 16:46:49,211 basehttp 12204 26104 "GET /auditorias/tipos-questao/ HTTP/1.1" 200 32129
INFO 2025-09-11 16:46:49,643 basehttp 12204 26104 "GET /auditorias/modelos-avaliacao/ HTTP/1.1" 200 32192
INFO 2025-09-11 16:46:50,636 basehttp 12204 26104 "GET /auditorias/modelos-avaliacao/criar/ HTTP/1.1" 200 41072
INFO 2025-09-11 16:46:54,024 basehttp 12204 26104 "GET /auditorias/modelos-avaliacao/criar/ HTTP/1.1" 200 41072
INFO 2025-09-11 16:48:12,015 basehttp 12204 26104 "GET /auditorias/modelos-avaliacao/criar/ HTTP/1.1" 200 41072
INFO 2025-09-11 16:48:13,242 basehttp 12204 26104 "GET /auditorias/dashboard/ HTTP/1.1" 200 36742
INFO 2025-09-11 16:48:15,182 basehttp 12204 26104 "GET /auditorias/auditorias/ HTTP/1.1" 200 32162
INFO 2025-09-11 16:48:15,747 basehttp 12204 26104 "GET /auditorias/dashboard/ HTTP/1.1" 200 36742
INFO 2025-09-11 16:48:43,388 basehttp 12204 26104 "GET /auditorias/dashboard/ HTTP/1.1" 200 36742
INFO 2025-09-11 16:48:49,209 basehttp 12204 26104 "GET /auditorias/auditorias/ HTTP/1.1" 200 32162
INFO 2025-09-11 16:48:51,090 basehttp 12204 26104 "GET /itens/ HTTP/1.1" 200 31971
INFO 2025-09-11 16:48:51,984 basehttp 12204 26104 "GET /auditorias/auditorias/ HTTP/1.1" 200 32162
INFO 2025-09-11 16:48:52,506 basehttp 12204 26104 "GET /itens/ HTTP/1.1" 200 31971
INFO 2025-09-11 16:48:53,096 basehttp 12204 26104 "GET /auditorias/pilares/ HTTP/1.1" 200 37535
INFO 2025-09-11 16:48:53,799 basehttp 12204 26104 "GET /auditorias/categorias/ HTTP/1.1" 200 32205
INFO 2025-09-11 16:48:54,701 basehttp 12204 26104 "GET /auditorias/pilares/ HTTP/1.1" 200 37535
INFO 2025-09-11 16:48:55,666 basehttp 12204 26104 "GET /auditorias/pilares/criar/ HTTP/1.1" 200 49261
INFO 2025-09-11 16:49:08,226 basehttp 12204 26104 "GET /auditorias/pilares/criar/ HTTP/1.1" 200 49261
INFO 2025-09-11 16:49:09,521 basehttp 12204 26104 "GET /auditorias/pilares/ HTTP/1.1" 200 37535
INFO 2025-09-11 16:49:10,200 basehttp 12204 26104 "GET /auditorias/categorias/ HTTP/1.1" 200 32205
INFO 2025-09-11 16:49:10,686 basehttp 12204 26104 "GET /auditorias/normas/ HTTP/1.1" 200 32000
INFO 2025-09-11 16:49:11,263 basehttp 12204 26104 "GET /auditorias/ferramentas-digitais/ HTTP/1.1" 200 32175
INFO 2025-09-11 16:49:12,468 basehttp 12204 26104 "GET /auditorias/tipos-questao/ HTTP/1.1" 200 32129
INFO 2025-09-11 16:49:13,016 basehttp 12204 26104 "GET /auditorias/modelos-avaliacao/ HTTP/1.1" 200 32192
INFO 2025-09-11 16:49:13,636 basehttp 12204 26104 "GET /auditorias/checklists/ HTTP/1.1" 200 32052
INFO 2025-09-11 16:49:15,649 basehttp 12204 26104 "GET /auditorias/modelos-auditoria/ HTTP/1.1" 200 32170
INFO 2025-09-11 16:49:53,737 basehttp 12204 26104 "GET /auditorias/dashboard/ HTTP/1.1" 200 36742
WARNING 2025-09-11 16:49:59,589 base 12204 26104 Method Not Allowed (GET): /logout/
WARNING 2025-09-11 16:49:59,600 log 12204 26104 Method Not Allowed: /logout/
WARNING 2025-09-11 16:49:59,600 basehttp 12204 26104 "GET /logout/ HTTP/1.1" 405 0
INFO 2025-09-11 16:50:04,671 basehttp 12204 26104 "GET / HTTP/1.1" 302 0
INFO 2025-09-11 16:50:04,704 basehttp 12204 26104 "GET /auditorias/dashboard/ HTTP/1.1" 200 36742
WARNING 2025-09-11 16:50:06,988 base 12204 26104 Method Not Allowed (GET): /logout/
WARNING 2025-09-11 16:50:07,001 log 12204 26104 Method Not Allowed: /logout/
WARNING 2025-09-11 16:50:07,001 basehttp 12204 26104 "GET /logout/ HTTP/1.1" 405 0
INFO 2025-09-11 16:50:09,188 basehttp 12204 26104 "GET / HTTP/1.1" 302 0
INFO 2025-09-11 16:50:09,226 basehttp 12204 26104 "GET /auditorias/dashboard/ HTTP/1.1" 200 36742
INFO 2025-09-11 16:50:18,650 basehttp 12204 14528 "GET /auditorias/dashboard/ HTTP/1.1" 302 0
INFO 2025-09-11 16:50:18,703 basehttp 12204 14528 "GET /login/?next=/auditorias/dashboard/ HTTP/1.1" 200 3431
INFO 2025-09-11 16:50:18,936 basehttp 12204 14528 "GET /static/css/login.css HTTP/1.1" 200 16500
INFO 2025-09-11 16:50:18,968 basehttp 12204 33008 "GET /static/img/imagem2.png HTTP/1.1" 200 153024
INFO 2025-09-11 16:50:18,985 basehttp 12204 18280 "GET /static/js/login.js HTTP/1.1" 200 4680
WARNING 2025-09-11 16:50:20,092 log 12204 18280 Not Found: /favicon.ico
WARNING 2025-09-11 16:50:20,092 basehttp 12204 18280 "GET /favicon.ico HTTP/1.1" 404 3484
INFO 2025-09-11 16:50:59,171 basehttp 12204 18280 "POST /login/?next=/auditorias/dashboard/ HTTP/1.1" 302 0
INFO 2025-09-11 16:50:59,190 basehttp 12204 18280 "GET /auditorias/dashboard/ HTTP/1.1" 200 36742
INFO 2025-09-11 16:51:48,211 basehttp 12204 26104 "GET /auditorias/dashboard/ HTTP/1.1" 200 36742
INFO 2025-09-11 16:51:50,854 basehttp 12204 26104 "GET /auditorias/dashboard/ HTTP/1.1" 200 36742
INFO 2025-09-11 16:51:51,802 basehttp 12204 26104 "GET /auditorias/auditorias/ HTTP/1.1" 200 32162
INFO 2025-09-11 16:51:52,653 basehttp 12204 26104 "GET /itens/ HTTP/1.1" 200 31971
INFO 2025-09-11 16:51:53,521 basehttp 12204 26104 "GET /auditorias/pilares/ HTTP/1.1" 200 37535
INFO 2025-09-11 16:51:54,045 basehttp 12204 26104 "GET /auditorias/categorias/ HTTP/1.1" 200 32205
INFO 2025-09-11 16:51:54,513 basehttp 12204 26104 "GET /auditorias/normas/ HTTP/1.1" 200 32000
INFO 2025-09-11 16:51:55,006 basehttp 12204 26104 "GET /auditorias/categorias/ HTTP/1.1" 200 32205
INFO 2025-09-11 16:51:55,486 basehttp 12204 26104 "GET /auditorias/pilares/ HTTP/1.1" 200 37535
INFO 2025-09-11 16:51:56,521 basehttp 12204 26104 "GET /itens/ HTTP/1.1" 200 31971
INFO 2025-09-11 16:51:57,047 basehttp 12204 26104 "GET /auditorias/auditorias/ HTTP/1.1" 200 32162
INFO 2025-09-11 16:51:57,462 basehttp 12204 26104 "GET /auditorias/dashboard/ HTTP/1.1" 200 36742
INFO 2025-09-11 16:52:01,998 basehttp 12204 26104 "GET /auditorias/auditorias/ HTTP/1.1" 200 32162
INFO 2025-09-11 16:52:02,569 basehttp 12204 26104 "GET /auditorias/dashboard/ HTTP/1.1" 200 36742
INFO 2025-09-11 16:52:04,653 basehttp 12204 26104 "GET /auditorias/auditorias/ HTTP/1.1" 200 32162
INFO 2025-09-11 16:52:05,074 basehttp 12204 26104 "GET /auditorias/dashboard/ HTTP/1.1" 200 36742
INFO 2025-09-11 16:52:21,994 basehttp 12204 26104 "GET /auditorias/auditorias/ HTTP/1.1" 200 32162
INFO 2025-09-11 16:52:27,048 basehttp 12204 26104 "GET /itens/ HTTP/1.1" 200 31971
INFO 2025-09-11 16:52:30,137 basehttp 12204 26104 "GET /auditorias/pilares/ HTTP/1.1" 200 37535
INFO 2025-09-11 16:52:32,844 basehttp 12204 26104 "GET /auditorias/categorias/ HTTP/1.1" 200 32205
INFO 2025-09-11 16:52:33,541 basehttp 12204 26104 "GET /auditorias/pilares/ HTTP/1.1" 200 37535
INFO 2025-09-11 16:52:33,998 basehttp 12204 26104 "GET /itens/ HTTP/1.1" 200 31971
INFO 2025-09-11 16:52:34,573 basehttp 12204 26104 "GET /auditorias/auditorias/ HTTP/1.1" 200 32162
INFO 2025-09-11 16:52:35,008 basehttp 12204 26104 "GET /auditorias/dashboard/ HTTP/1.1" 200 36742
INFO 2025-09-11 16:52:36,736 basehttp 12204 26104 "GET /auditorias/pilares/ HTTP/1.1" 200 37535
INFO 2025-09-11 16:52:37,377 basehttp 12204 26104 "GET /auditorias/categorias/ HTTP/1.1" 200 32205
INFO 2025-09-11 16:52:38,894 basehttp 12204 26104 "GET /auditorias/dashboard/ HTTP/1.1" 200 36742
INFO 2025-09-11 16:52:39,484 basehttp 12204 26104 "GET /auditorias/auditorias/ HTTP/1.1" 200 32162
INFO 2025-09-11 16:52:40,379 basehttp 12204 26104 "GET /itens/ HTTP/1.1" 200 31971
INFO 2025-09-11 16:52:41,149 basehttp 12204 26104 "GET /auditorias/pilares/ HTTP/1.1" 200 37535
INFO 2025-09-11 16:52:41,815 basehttp 12204 26104 "GET /auditorias/categorias/ HTTP/1.1" 200 32205
INFO 2025-09-11 16:52:49,714 basehttp 12204 26104 "GET /auditorias/dashboard/ HTTP/1.1" 200 36742
INFO 2025-09-11 16:52:55,203 basehttp 12204 26104 "GET /auditorias/pilares/ HTTP/1.1" 200 37535
INFO 2025-09-11 16:52:56,026 basehttp 12204 26104 "GET /itens/ HTTP/1.1" 200 31971
INFO 2025-09-11 16:52:56,586 basehttp 12204 26104 "GET /auditorias/auditorias/ HTTP/1.1" 200 32162
INFO 2025-09-11 16:52:57,209 basehttp 12204 26104 "GET /auditorias/dashboard/ HTTP/1.1" 200 36742
